"""添加 min_stock 字段

Revision ID: 91827e61a3f4
Revises: e3def861ab18
Create Date: 2026-09-10 23:16:03.464910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91827e61a3f4'
down_revision: Union[str, Sequence[str], None] = 'e3def861ab18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('min_stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'min_stock')
    # ### end Alembic commands ###
