"""添加仓库表和商品关联

Revision ID: bd05ca534669
Revises: 559fe0bdf74f
Create Date: 2026-09-12 02:19:38.110248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd05ca534669'
down_revision: Union[str, Sequence[str], None] = '559fe0bdf74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_warehouse_id'), 'products', ['warehouse_id'], unique=False)
    op.drop_constraint(op.f('products_ibfk_3'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_ibfk_3'), 'products', 'brands', ['brand_id'], ['id'])
    op.drop_index(op.f('ix_products_warehouse_id'), table_name='products')
    op.drop_column('products', 'warehouse_id')
    # ### end Alembic commands ###
