"""添加order_id

Revision ID: f1e2d04ae358
Revises: dd7d51ed3f04
Create Date: 2026-09-11 00:38:51.509187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e2d04ae358'
down_revision: Union[str, Sequence[str], None] = 'dd7d51ed3f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_logs', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_logs_order_id'), 'inventory_logs', ['order_id'], unique=False)
    op.create_foreign_key(None, 'inventory_logs', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_logs', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_logs_order_id'), table_name='inventory_logs')
    op.drop_column('inventory_logs', 'order_id')
    # ### end Alembic commands ###
